stages:
   - build


before_script:
    - test -n "$DEBPKGS" && (apt-get update && apt-get install -y --no-install-recommend $DEBPKGS)
    - $CC --version


.script: &build_and_test
    - make
    - ./build/mred.bin --version
    - make check


.script: &apt_install


build_gcc:
    stage: build
    only:
        - next
    image: gcc
    variables:
        CC: gcc
        DEPKGS:
    script: *build_and_test


test_valgrind:
    stage: build
    only:
        - next
    image: debian:stable
    variables:
        CC: clang
        DEPKGS: clang valgrind
    script: *build_and_test
        - make check-valgrind
