stages:
   - build

before_script:
    - env | sort
    - test -n "$DEBPKGS" && (apt-get update && apt-get install -y --no-install-recommends $DEBPKGS)
    - $CC --version

.script: &build_and_test
    - make
    - ./build/mred.bin --version
    - make check
    - test "true" = "$CHECK_VALGRIND" && make check-valgrind

build_gcc:
    stage: build
    only:
        - next
    image: gcc
    variables:
        CC: gcc
        DEBPKGS: ""
        CHECK_VALGRIND: "false"
    script: *build_and_test

test_valgrind:
    stage: build
    only:
        - next
    image: debian:stable
    variables:
        CC: clang
        DEBPKGS: clang valgrind
        CHECK_VALGRIND: "true"
    script: *build_and_test
