stages:
   - build

before_script:
    - cc --version

.script: &build_script
    - make
    - ./build/mred.bin --version

build_gcc:
    stage: build
    only:
        - next
    image: gcc
    script: *build_script
